dist: xenial
sudo: required

language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake gcc libtool libssl-dev make unzip xsltproc
  - sudo mkdir -p -m 0755 /var/empty

script:
  - pwd
