dist: xenial
sudo: required

language: c

before_install:
  - pwd
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake gcc libtool libssl-dev make unzip xsltproc
  - sudo mkdir -p -m 0755 /var/empty

script:
  - pwd
  - echo "Home dir is" $HOME
  - export LIBOQS_INSTALL=/tmp/liboqs-install
  - export OPENSSH_INSTALL=/tmp/openssh-install
  - autoreconf
  - ./configure --enable-pq-kex --enable-hybrid-kex --prefix=$OPENSSH_INSTALL --sysconfdir=$OPENSSH_INSTALL --with-liboqs-dir=$LIBOQS_INSTALL
  - make -j
  - make install
  - make tests
